"""create pharmacy inventory table

Revision ID: 072c72c66e38
Revises: ed167374c89b
Create Date: 2026-07-30 14:42:45.744048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072c72c66e38'
down_revision: Union[str, Sequence[str], None] = 'ed167374c89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_inventory',
    sa.Column('pharmacy_inventory_code', sa.String(length=20), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number')
    )
    op.create_index(op.f('ix_pharmacy_inventory_id'), 'pharmacy_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_pharmacy_inventory_code'), 'pharmacy_inventory', ['pharmacy_inventory_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_inventory_pharmacy_inventory_code'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_id'), table_name='pharmacy_inventory')
    op.drop_table('pharmacy_inventory')
    # ### end Alembic commands ###
