"""create batch tracking table

Revision ID: 122fa9d6298e
Revises: dc7ac0616e42
Create Date: 2026-07-30 15:39:21.511763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122fa9d6298e'
down_revision: Union[str, Sequence[str], None] = 'dc7ac0616e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_tracking',
    sa.Column('batch_tracking_code', sa.String(length=20), nullable=False),
    sa.Column('pharmacy_inventory_id', sa.Integer(), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=False),
    sa.Column('recall_status', sa.String(length=30), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_inventory_id'], ['pharmacy_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_tracking_batch_tracking_code'), 'batch_tracking', ['batch_tracking_code'], unique=True)
    op.create_index(op.f('ix_batch_tracking_id'), 'batch_tracking', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_tracking_id'), table_name='batch_tracking')
    op.drop_index(op.f('ix_batch_tracking_batch_tracking_code'), table_name='batch_tracking')
    op.drop_table('batch_tracking')
    # ### end Alembic commands ###
