"""create hospitals table

Revision ID: 1f73834be05d
Revises: 241393901b04
Create Date: 2026-07-29 00:21:07.035336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f73834be05d'
down_revision: Union[str, Sequence[str], None] = '241393901b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('registration_number', sa.String(length=100), nullable=False))
    op.add_column('hospitals', sa.Column('emergency_contact', sa.String(length=20), nullable=True))
    op.add_column('hospitals', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('hospitals', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_index(op.f('hospital_code'), table_name='hospitals')
    op.create_index(op.f('ix_hospitals_hospital_code'), 'hospitals', ['hospital_code'], unique=True)
    op.create_index(op.f('ix_hospitals_hospital_name'), 'hospitals', ['hospital_name'], unique=False)
    op.create_unique_constraint(None, 'hospitals', ['registration_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospitals', type_='unique')
    op.drop_index(op.f('ix_hospitals_hospital_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_hospital_code'), table_name='hospitals')
    op.create_index(op.f('hospital_code'), 'hospitals', ['hospital_code'], unique=True)
    op.alter_column('hospitals', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('hospitals', 'description')
    op.drop_column('hospitals', 'emergency_contact')
    op.drop_column('hospitals', 'registration_number')
    # ### end Alembic commands ###
