"""create sample collections table

Revision ID: 3ab4f3489ab4
Revises: 84ee6c3ce441
Create Date: 2026-07-30 12:56:58.886240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab4f3489ab4'
down_revision: Union[str, Sequence[str], None] = '84ee6c3ce441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_collections',
    sa.Column('sample_collection_code', sa.String(length=20), nullable=False),
    sa.Column('lab_order_id', sa.Integer(), nullable=False),
    sa.Column('sample_type', sa.String(length=100), nullable=False),
    sa.Column('sample_container', sa.String(length=100), nullable=True),
    sa.Column('collected_by', sa.String(length=150), nullable=False),
    sa.Column('collection_datetime', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_collections_id'), 'sample_collections', ['id'], unique=False)
    op.create_index(op.f('ix_sample_collections_sample_collection_code'), 'sample_collections', ['sample_collection_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_collections_sample_collection_code'), table_name='sample_collections')
    op.drop_index(op.f('ix_sample_collections_id'), table_name='sample_collections')
    op.drop_table('sample_collections')
    # ### end Alembic commands ###
