"""create ambulances table

Revision ID: 44ca29659b8d
Revises: 6af1e8d9a24a
Create Date: 2026-07-29 21:29:55.328565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ca29659b8d'
down_revision: Union[str, Sequence[str], None] = '6af1e8d9a24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulances',
    sa.Column('ambulance_code', sa.String(length=20), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('driver_phone', sa.String(length=20), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_number')
    )
    op.create_index(op.f('ix_ambulances_ambulance_code'), 'ambulances', ['ambulance_code'], unique=True)
    op.create_index(op.f('ix_ambulances_id'), 'ambulances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ambulances_id'), table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_ambulance_code'), table_name='ambulances')
    op.drop_table('ambulances')
    # ### end Alembic commands ###
