"""create expiry management table

Revision ID: 4af25195d207
Revises: 122fa9d6298e
Create Date: 2026-07-30 15:41:47.075581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af25195d207'
down_revision: Union[str, Sequence[str], None] = '122fa9d6298e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expiry_management',
    sa.Column('expiry_code', sa.String(length=20), nullable=False),
    sa.Column('pharmacy_inventory_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('expiry_status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by', sa.String(length=150), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_inventory_id'], ['pharmacy_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expiry_management_expiry_code'), 'expiry_management', ['expiry_code'], unique=True)
    op.create_index(op.f('ix_expiry_management_id'), 'expiry_management', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expiry_management_id'), table_name='expiry_management')
    op.drop_index(op.f('ix_expiry_management_expiry_code'), table_name='expiry_management')
    op.drop_table('expiry_management')
    # ### end Alembic commands ###
