"""create surgeries table

Revision ID: 4d90f48f5d68
Revises: 7664239a2efb
Create Date: 2026-07-29 23:52:46.434222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d90f48f5d68'
down_revision: Union[str, Sequence[str], None] = '7664239a2efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surgeries',
    sa.Column('surgery_code', sa.String(length=20), nullable=False),
    sa.Column('emr_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('surgery_name', sa.String(length=255), nullable=False),
    sa.Column('surgery_date', sa.Date(), nullable=False),
    sa.Column('operation_theater', sa.String(length=100), nullable=True),
    sa.Column('anesthesia_type', sa.String(length=100), nullable=True),
    sa.Column('surgeon', sa.String(length=255), nullable=True),
    sa.Column('assistant_surgeon', sa.String(length=255), nullable=True),
    sa.Column('surgery_notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['emr_id'], ['emr.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surgeries_id'), 'surgeries', ['id'], unique=False)
    op.create_index(op.f('ix_surgeries_surgery_code'), 'surgeries', ['surgery_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surgeries_surgery_code'), table_name='surgeries')
    op.drop_index(op.f('ix_surgeries_id'), table_name='surgeries')
    op.drop_table('surgeries')
    # ### end Alembic commands ###
