"""create emr table

Revision ID: 66e0fc68e540
Revises: 4566f14ef4b3
Create Date: 2026-07-29 22:58:07.429650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e0fc68e540'
down_revision: Union[str, Sequence[str], None] = '4566f14ef4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emr',
    sa.Column('emr_code', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('opd_id', sa.Integer(), nullable=True),
    sa.Column('ipd_id', sa.Integer(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('family_history', sa.Text(), nullable=True),
    sa.Column('allergy_history', sa.Text(), nullable=True),
    sa.Column('examination', sa.Text(), nullable=True),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('treatment_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['ipd_id'], ['ipd.id'], ),
    sa.ForeignKeyConstraint(['opd_id'], ['opd.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_emr_code'), 'emr', ['emr_code'], unique=True)
    op.create_index(op.f('ix_emr_id'), 'emr', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emr_id'), table_name='emr')
    op.drop_index(op.f('ix_emr_emr_code'), table_name='emr')
    op.drop_table('emr')
    # ### end Alembic commands ###
