"""create refunds table

Revision ID: 7fb746cacfd4
Revises: 906faa242713
Create Date: 2026-07-30 21:16:13.420589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb746cacfd4'
down_revision: Union[str, Sequence[str], None] = '906faa242713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('refund_code', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refund_date', sa.DateTime(), nullable=False),
    sa.Column('refund_reason', sa.Text(), nullable=False),
    sa.Column('refund_status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.create_index(op.f('ix_refunds_refund_code'), 'refunds', ['refund_code'], unique=True)
    op.add_column('insurance_claims', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('insurance_claims', sa.Column('approval_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'insurance_claims', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insurance_claims', type_='foreignkey')
    op.drop_column('insurance_claims', 'approval_date')
    op.drop_column('insurance_claims', 'approved_by')
    op.drop_index(op.f('ix_refunds_refund_code'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
