"""create lab orders table

Revision ID: 84ee6c3ce441
Revises: 4d90f48f5d68
Create Date: 2026-07-30 12:53:50.317985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ee6c3ce441'
down_revision: Union[str, Sequence[str], None] = '4d90f48f5d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discharge_summaries',
    sa.Column('discharge_summary_code', sa.String(length=20), nullable=False),
    sa.Column('ipd_id', sa.Integer(), nullable=False),
    sa.Column('emr_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=False),
    sa.Column('final_diagnosis', sa.Text(), nullable=False),
    sa.Column('procedures_performed', sa.Text(), nullable=True),
    sa.Column('hospital_course', sa.Text(), nullable=True),
    sa.Column('condition_at_discharge', sa.Text(), nullable=True),
    sa.Column('discharge_medications', sa.Text(), nullable=True),
    sa.Column('follow_up_instructions', sa.Text(), nullable=True),
    sa.Column('discharge_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['emr_id'], ['emr.id'], ),
    sa.ForeignKeyConstraint(['ipd_id'], ['ipd.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discharge_summaries_discharge_summary_code'), 'discharge_summaries', ['discharge_summary_code'], unique=True)
    op.create_index(op.f('ix_discharge_summaries_id'), 'discharge_summaries', ['id'], unique=False)
    op.create_table('lab_orders',
    sa.Column('lab_order_code', sa.String(length=20), nullable=False),
    sa.Column('emr_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('test_category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['emr_id'], ['emr.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_orders_id'), 'lab_orders', ['id'], unique=False)
    op.create_index(op.f('ix_lab_orders_lab_order_code'), 'lab_orders', ['lab_order_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_orders_lab_order_code'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_id'), table_name='lab_orders')
    op.drop_table('lab_orders')
    op.drop_index(op.f('ix_discharge_summaries_id'), table_name='discharge_summaries')
    op.drop_index(op.f('ix_discharge_summaries_discharge_summary_code'), table_name='discharge_summaries')
    op.drop_table('discharge_summaries')
    # ### end Alembic commands ###
