"""create prescription validations table

Revision ID: 87edea206d9d
Revises: 072c72c66e38
Create Date: 2026-07-30 14:48:12.647166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87edea206d9d'
down_revision: Union[str, Sequence[str], None] = '072c72c66e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_validations',
    sa.Column('validation_code', sa.String(length=20), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_inventory_id', sa.Integer(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('approved_quantity', sa.Integer(), nullable=False),
    sa.Column('validation_status', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.String(length=150), nullable=False),
    sa.Column('validation_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_inventory_id'], ['pharmacy_inventory.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_validations_id'), 'prescription_validations', ['id'], unique=False)
    op.create_index(op.f('ix_prescription_validations_validation_code'), 'prescription_validations', ['validation_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_validations_validation_code'), table_name='prescription_validations')
    op.drop_index(op.f('ix_prescription_validations_id'), table_name='prescription_validations')
    op.drop_table('prescription_validations')
    # ### end Alembic commands ###
