"""create treatment plan table

Revision ID: 903b8ca15d31
Revises: 726c123fee4f
Create Date: 2026-07-29 23:46:22.389019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903b8ca15d31'
down_revision: Union[str, Sequence[str], None] = '726c123fee4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_plans',
    sa.Column('treatment_plan_code', sa.String(length=20), nullable=False),
    sa.Column('emr_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('treatment_title', sa.String(length=255), nullable=False),
    sa.Column('treatment_description', sa.Text(), nullable=True),
    sa.Column('treatment_goals', sa.Text(), nullable=True),
    sa.Column('follow_up_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['emr_id'], ['emr.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plans_id'), 'treatment_plans', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_treatment_plan_code'), 'treatment_plans', ['treatment_plan_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_plans_treatment_plan_code'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    # ### end Alembic commands ###
