"""create insurance claims table

Revision ID: 906faa242713
Revises: 297ace260cd2
Create Date: 2026-07-30 19:39:24.397735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906faa242713'
down_revision: Union[str, Sequence[str], None] = '297ace260cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_claims',
    sa.Column('claim_code', sa.String(length=20), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('insurance_provider', sa.String(length=150), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('claim_status', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claims_claim_code'), 'insurance_claims', ['claim_code'], unique=True)
    op.create_index(op.f('ix_insurance_claims_id'), 'insurance_claims', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_claims_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_claim_code'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    # ### end Alembic commands ###
