"""create test processing table

Revision ID: af7766f32ef6
Revises: 3ab4f3489ab4
Create Date: 2026-07-30 13:13:54.647982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7766f32ef6'
down_revision: Union[str, Sequence[str], None] = '3ab4f3489ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_processing',
    sa.Column('processing_code', sa.String(length=20), nullable=False),
    sa.Column('lab_order_id', sa.Integer(), nullable=False),
    sa.Column('processed_by', sa.String(length=150), nullable=False),
    sa.Column('processing_start', sa.DateTime(), nullable=False),
    sa.Column('processing_end', sa.DateTime(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_processing_id'), 'test_processing', ['id'], unique=False)
    op.create_index(op.f('ix_test_processing_processing_code'), 'test_processing', ['processing_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_processing_processing_code'), table_name='test_processing')
    op.drop_index(op.f('ix_test_processing_id'), table_name='test_processing')
    op.drop_table('test_processing')
    # ### end Alembic commands ###
