"""create beds table

Revision ID: ba1ab7a8c053
Revises: a8a297dc0684
Create Date: 2026-07-29 21:12:32.047366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1ab7a8c053'
down_revision: Union[str, Sequence[str], None] = 'a8a297dc0684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beds',
    sa.Column('bed_code', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('bed_type', sa.String(length=50), nullable=False),
    sa.Column('bed_status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bed_number')
    )
    op.create_index(op.f('ix_beds_bed_code'), 'beds', ['bed_code'], unique=True)
    op.create_index(op.f('ix_beds_id'), 'beds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beds_id'), table_name='beds')
    op.drop_index(op.f('ix_beds_bed_code'), table_name='beds')
    op.drop_table('beds')
    # ### end Alembic commands ###
