"""create hospitals table

Revision ID: bdf2f5d5da3b
Revises: 1f73834be05d
Create Date: 2026-07-29 13:13:31.072039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bdf2f5d5da3b'
down_revision: Union[str, Sequence[str], None] = '1f73834be05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospitals', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_index(op.f('ix_hospitals_hospital_name'), table_name='hospitals')
    op.drop_index(op.f('tax_number'), table_name='hospitals')
    op.drop_column('hospitals', 'tax_number')
    op.drop_column('hospitals', 'logo')
    op.drop_column('hospitals', 'emergency_contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('emergency_contact', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('hospitals', sa.Column('logo', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('hospitals', sa.Column('tax_number', mysql.VARCHAR(length=100), nullable=True))
    op.create_index(op.f('tax_number'), 'hospitals', ['tax_number'], unique=True)
    op.create_index(op.f('ix_hospitals_hospital_name'), 'hospitals', ['hospital_name'], unique=False)
    op.alter_column('hospitals', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
