"""remove billing id from payments

Revision ID: d6e78c848877
Revises: d51981077926
Create Date: 2026-07-31 17:15:09.622409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e78c848877'
down_revision: Union[str, Sequence[str], None] = 'd51981077926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('billing_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payments', 'billings', ['billing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'billing_id')
    # ### end Alembic commands ###
