"""create drug stock management table

Revision ID: dc7ac0616e42
Revises: e5cb9f21c2d2
Create Date: 2026-07-30 15:36:40.929688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7ac0616e42'
down_revision: Union[str, Sequence[str], None] = 'e5cb9f21c2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_stock_management',
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('pharmacy_inventory_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('previous_quantity', sa.Integer(), nullable=False),
    sa.Column('updated_quantity', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=150), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_inventory_id'], ['pharmacy_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_stock_management_id'), 'drug_stock_management', ['id'], unique=False)
    op.create_index(op.f('ix_drug_stock_management_stock_code'), 'drug_stock_management', ['stock_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drug_stock_management_stock_code'), table_name='drug_stock_management')
    op.drop_index(op.f('ix_drug_stock_management_id'), table_name='drug_stock_management')
    op.drop_table('drug_stock_management')
    # ### end Alembic commands ###
