"""create medicine dispensings table

Revision ID: e5cb9f21c2d2
Revises: 87edea206d9d
Create Date: 2026-07-30 15:32:26.448653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5cb9f21c2d2'
down_revision: Union[str, Sequence[str], None] = '87edea206d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_dispensings',
    sa.Column('dispensing_code', sa.String(length=20), nullable=False),
    sa.Column('prescription_validation_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_inventory_id', sa.Integer(), nullable=False),
    sa.Column('dispensed_quantity', sa.Integer(), nullable=False),
    sa.Column('dispensed_by', sa.String(length=150), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_inventory_id'], ['pharmacy_inventory.id'], ),
    sa.ForeignKeyConstraint(['prescription_validation_id'], ['prescription_validations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_dispensings_dispensing_code'), 'medicine_dispensings', ['dispensing_code'], unique=True)
    op.create_index(op.f('ix_medicine_dispensings_id'), 'medicine_dispensings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicine_dispensings_id'), table_name='medicine_dispensings')
    op.drop_index(op.f('ix_medicine_dispensings_dispensing_code'), table_name='medicine_dispensings')
    op.drop_table('medicine_dispensings')
    # ### end Alembic commands ###
